### ISSUE TITLE
addrev needs adjusting for release commits

### ISSUE THREAD

**Issue by mattcaswell** [openssl/tools#112]
The new rules that say the author cannot be one of the reviewers of a pull request do not apply to release commits and CHANGES/NEWS updates. But addrev doesn't know about this special case and refuses to add the appropriate headers.

**Comment by mattcaswell** [comment]
I imagine a new "--release" argument to tell addrev that the commits in question are for a release and therefore the normal rules are relaxed.

The release script in the master/3.0 branches should be adjusted to use this feature if that is the way we go.

**Comment by levitte** [comment]
I just looked at [known trailers](https://git.wiki.kernel.org/index.php/CommitMessageConventions).  Suggested trailer for this:

```
Release: x.y.z
```

With x.y.z being the new version that the commits are intended for

**Comment by mattcaswell** [comment]
This was done...although isn't quite right. I will create a new issue for the problem. Closing this.
