### ISSUE TITLE
addrev shouldn't require two reviewers for the web or tools repos

### ISSUE THREAD

**Issue by levitte** [openssl/tools#113]
It was decided that the main repository needed the extra pair of eyes unconditionally.
However, it's not certain that the web and tools repos were under the same kind of consideration.

**Comment by mspncp** [comment]
Why not? For me it makes equal sense in every repository.

**Comment by t-j-h** [comment]
We changed the policy for the committers so it inherently was scoped to the repositories the committers have write access to update. I don't see a reason we cannot apply it on other repositories too - but that would clearly be a separate decision to make.

How is that for agreeing with both of you at once :-)

**Comment by paulidale** [comment]
> Why not? For me it makes equal sense in every repository.

We hit a problem with OMC reviews.  An OMC repo that requires two independent reviews means half the OMC is involved.  We might as well have a vote on every change, and have no reviews.

**Comment by levitte** [comment]
I could go for two reviewers on the tools repo, though.  See https://github.com/openssl/tools/pull/114/files#r842406002

**Comment by mspncp** [comment]
> > Why not? For me it makes equal sense in every repository.
> 
> We hit a problem with OMC reviews. An OMC repo that requires two independent reviews means half the OMC is involved. We might as well have a vote on every change, and have no reviews.

Two independent OMC approvals are still more lightweight than an OMC vote. 🤔

**Comment by levitte** [comment]
> Two independent OMC approvals are still more lightweight than an OMC vote. thinking

It's still more churn, and more so because the OMC is relatively small.  It makes changes like openssl/web#318, which really is a pretty quick and easy thing, not quite so quick.

**Comment by mspncp** [comment]
Well, then let it be one other OMC member and one committer.

**Comment by mspncp** [comment]
I have another suggestion:  outstanding change requests should be merge blockers, even if the approval quota has been reached. IMHO the grace period gives enough time to issue a re-review request. And if that goes unanswered, the change request should be formally dismissed (with a comment that it has been addressed resp. rejected).

**Comment by levitte** [comment]
This has been satisfied with #114, so closing.
(why I didn't link that PR to this issue, I do not know...)
