### ISSUE TITLE
addrev script can't locate OpenSSL/Query/REST.pm

### ISSUE THREAD

**Issue by mspncp** [openssl/tools#134]
It seems like my addrev script stopped working a while ago. (Don't know when, haven't been using it for a while).

```
msp@office:~/src/openssl/master$ addrev --prnum=20106 @beldmit
Rewrite 8eaa815234dc00804c07d6ab7a1e5d7283c81df8 (1/1) (0 seconds passed, remaining 0 predicted)    Can't locate OpenSSL/Query/REST.pm in @INC (you may need to install the OpenSSL::Query::REST module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /home/msp/openssl/tools/review-tools/gitaddrev line 9.
BEGIN failed--compilation aborted at /home/msp/openssl/tools/review-tools/gitaddrev line 9.
msg filter failed: gitaddrev --prnum=20106 --reviewer=@abc --myemail=xxx@ncp-e.com
 
addrev failed
Died at /home/msp/openssl/tools/review-tools/addrev line 89.
```

I checked that my tools directory is up-to-date
```
msp@office:~/src/openssl/master$ which addrev
/home/msp/openssl/tools/review-tools/addrev
msp@office:~/src/openssl/master$ cd /home/msp/openssl/tools/
msp@office:~/openssl/tools$ git log --oneline -1
ec24476 pick-to-branch: fix exit message by making variable name consistent
```
and the review-tools/README tells me to look for a README.md in the OpenSSL-Query folder:

https://github.com/openssl/tools/blob/ec24476e796cd39ea6b44ae8139b768a4a166c43/review-tools/README#L6

The README.md however has been removed in commit 0d8b3195d26d3382e4580633b49e0626225dfdad by @levitte.

What am I missing?

**Comment by mspncp** [comment]
cc @levitte

**Comment by DDvO** [comment]
I just had the same issue after some changes to my Perl installation.

I'm not happy either with `OpenSSL-Query/README.md` etc. having been moved away from here to https://github.com/openssl/omc-tools, which - as a regular Committer - I otherwise would not need.

Yet the following worked for me almost as described in the [README.md](https://github.com/openssl/omc-tools/blob/master/OpenSSL-Query/README.md) - I just had to add `sudo`:
```
git clone git@github.com:openssl/omc-tools.git
cd omc-tools/OpenSSL-Query
perl Makefile.PL
make && sudo make install
```

**Comment by levitte** [comment]
Hmmm...  moving OpenSSL-Query was a mistake, for sure.

I'll add it back to this repository.

**Comment by levitte** [comment]
(sorry @mspncp, this got lost in noise)

**Comment by mspncp** [comment]
No problem @levitte. I know y'all are very busy these days, and it was not an urgent issue. (I simply avoided merging pull requests 😆)

**Comment by DDvO** [comment]
I just stumbled over this issue again, after moving to a different machine under MacOS.
The slightly adapted recipe I mentioned above:
```
git clone git@github.com:openssl/omc-tools.git
cd omc-tools/OpenSSL-Query
perl Makefile.PL
make && sudo make install
``` 
worked on MacOS as well.

@levitte please do not forget moving that back to the `tools` repo and documenting it there.

**Comment by DDvO** [comment]
`wget https://api.openssl.org/0/Person/dev%40ddvo.net/ValueOfTag/rev` does work,
and the query also works in my browser.

The Perl installation must be missing some trust anchor cert(s).
A workaround is to replace all `https` schemes used by those Perl modules by `http` (which is ugly)
or to use for instance`sudo cpan Mozilla::CA` but I do not really wanna make Perl trust all those wonderful root CAs.

**Comment by mspncp** [comment]
Finally, I found the time to fix my addrev script. Thanks to @DDvO's notes, it was really easy.

See also https://github.com/openssl/omc-tools/pull/25.

**Comment by levitte** [comment]
Move implemented in two PRs: #170 and openssl/omc-tools#27

**Comment by mspncp** [comment]
Thanks @levitte!

**Comment by DDvO** [comment]
For the records, after the above mentioned move, the recipe given above becomes:
```
git clone git@github.com:openssl/tools.git
cd tools/OpenSSL-Query
perl Makefile.PL
make && sudo make install
```
