### ISSUE TITLE
`addrev` fails with `Server error: Can't verify SSL peers without knowing which Certificate Authorities to trust`

### ISSUE THREAD

**Issue by DDvO** [openssl/tools#163]
`gitaddrev` (regardless of any parameters provided) gives me this:
```
Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.30/OpenSSL/Query/PersonREST.pm line 75.
Server error: Can't verify SSL peers without knowing which Certificate Authorities to trust at /Library/Perl/5.30/OpenSSL/Query.pm line 118.
 at [...]/tools/review-tools/gitaddrev line 42.
```
Maybe this issue is specific to MacOS.

I got this after successfully installing the Perl support as mentioned in https://github.com/openssl/tools/issues/134#issuecomment-1663375737.

**Comment by DDvO** [comment]
The `Use of uninitialized value in concatenation (.) or string at /Library/Perl/5.30/OpenSSL/Query/PersonREST.pm line 75.`
part is because `$id` is not initialiized.
Silly that Perl does not report which variable (within a possibly complex expression) is uninitialized.

**Comment by DDvO** [comment]
`wget https://api.openssl.org/0/Person/dev%40ddvo.net/ValueOfTag/rev` does work,
and the query also works in my browser.

The Perl installation must be missing some trust anchor cert(s).
A workaround is to replace all `https` schemes used by those Perl modules by `http` (which is ugly)
or to use for instance`sudo cpan Mozilla::CA` but I do not really wanna make Perl trust all those wonderful root CAs.

**Comment by t8m** [comment]
Is this still an issue?

**Comment by DDvO** [comment]
I'm not sure.
I've just tried to reproduce and for instance
```
gitaddrev --list
addrev --myemail=dev@ddvo.net --prnum=...
```
currently work for me (also without `GIT_AUTHOR_EMAIL`).

I cannot recall, maybe in the end I used the workaround `sudo cpan Mozilla::CA`

**Comment by t8m** [comment]
I do not think we want to do some special handling of CA certs in gitaddrev.

I am closing this.

**Comment by DDvO** [comment]
The issue happened to me today again, so something is still not working smoothy.

After using the workaround `sudo cpan Mozilla::CA` again, it works again for me.
