### ISSUE TITLE
ghmerge creates wrong link 

### ISSUE THREAD

**Issue by richsalz** [openssl/tools#41]
The "merged from" line is wrong if not in the openssl repo:
```
- Log -----------------------------------------------------------------
commit fe185a2b8f12669f7a9a88582cb63ad316cd2382
Author: Dr. Matthias St. Pierre <Matthias.St.Pierre@ncp-e.com>
Date:   Wed Aug 14 01:24:55 2019 +0200

...    
    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/40)
```

**Comment by richsalz** [comment]
This fix is probably to change https://github.com/openssl/tools/blob/master/review-tools/gitaddrev#L24 to look at "git remote -v" and to determine the repo.

**Comment by levitte** [comment]
This has been "fixed" with flags to `addrev` telling it what remote repo we're working against...
