### ISSUE TITLE
addrev: Recent strong warning with newer git versions

### ISSUE THREAD

**Issue by levitte** [openssl/tools#48]
When using addrev just now, I got this big fat warning:

```
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...
```

It took about a second or two before the last line appeared.

I didn't interrupt this because I'm confident in what addrev does and that I can recover from mistakes ('cause I've done them), but addrev should probably be reworked to use filter-repo anyway.

**Comment by mspncp** [comment]
Thanks for the heads-up. Which git version are you using?

FWIW: [the patch](https://patchwork.kernel.org/patch/11128605) which introduced the change has a long explaining commit message.

**Comment by mspncp** [comment]
FWIW: After upgrading git to v2.24.1, I'm now getting this warning too when using review-tools/addrev.

**Comment by levitte** [comment]
The warning is silenced in `addrev`, see #81
