### ISSUE TITLE
Notifications on ready-to-merge

### ISSUE THREAD

**Issue by mattcaswell** [openssl/tools#52]
It would be nice if we sent out a notification to openssl-commits when a PR becomes ready-to-merge, mentioning the reviewer names in the notification as a reminder that they might want to come back and merge the PR

**Comment by iamamoose** [comment]
Would it be good enough to auto add a comment to the PR (like this one) that does like @mattcaswell @iamamoose or you think it needs an out of github email?

**Comment by mattcaswell** [comment]
Mentioning in a comment seems ideal. That way github will notify the user in whichever way they prefer to receive their notifications (which could be email, or via dashboard).

**Comment by mspncp** [comment]
There is no need to mention anybody particular, because everybody who participated in the discussion (which includes the reviewers)!is automatically subscribed to the thread. At least that’s GitHub‘s default setting. 

So posting a simple „This pull request is ready to merge“ is sufficient.
