### ISSUE TITLE
Do CLA trivial label magic

### ISSUE THREAD

**Issue by iamamoose** [openssl/tools#63]
Why wasn't the CLA: trivial label set earlier?  AFAIK there is no automatic labelling if a commit contains "CLA: trivial" in the header.It's purely manual. Perhaps @iamamoose could work his magic...?

**Comment by levitte** [comment]
#49 has a fix for that, but it has remained untested.  Would you mind eye-balling it?

**Comment by iamamoose** [comment]
covered by ^
